name: Cargo test

on:
  push:
    branches: [ "main", "gh" ]
  pull_request:
    branches: [ "main", "gh" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on latest Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --verbose --features=bin
  lint:
    name: Lint check on latest Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run clippy
      run: cargo clippy --verbose --features=bin
    - name: Make annotation
      run: if ! cargo clippy --quiet --features=bin -- -D warnings; then echo "::warning::Lint check failed"; fi
